/* AUTO-GENERATED by tools/bls12_381_port/gen_g_test_vectors.py */
/* Tests g1_scalar_mul and g2_scalar_mul against py_ecc.       */
#pragma once
#include <stdint.h>

#define NUM_G1_TEST_VECTORS 7
#define NUM_G2_TEST_VECTORS 7

/* Scalar field order q (in 8 little-endian uint32_t limbs) */
static const uint32_t BLS_Q_8LIMB[8] = {
    0x00000001, 0xffffffff, 0xfffe5bfe, 0x53bda402,
    0x09a1d805, 0x3339d808, 0x299d7d48, 0x73eda753
};

/* ===== G1 test vectors ===== */

/* g1_k1: k = 0x1 */
static const uint32_t g1_k1_k[8] = {
    0x00000001, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000
};
static const uint32_t g1_k1_x[12] = {
    0xfd530c16, 0x5cb38790, 0x9976fff5, 0x7817fc67,
    0x143ba1c1, 0x154f95c7, 0xf3d0e747, 0xf0ae6acd,
    0x21dbf440, 0xedce6ecc, 0x9e0bfb75, 0x12017741
};
static const uint32_t g1_k1_y[12] = {
    0x0ce72271, 0xbaac93d5, 0x7918fd8e, 0x8c22631a,
    0x570725ce, 0xdd595f13, 0x50405194, 0x51ac5829,
    0xad0059c0, 0x0e1c8c3f, 0x5008a26a, 0x0bbc3efc
};

/* g1_k2: k = 0x2 */
static const uint32_t g1_k2_k[8] = {
    0x00000002, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000
};
static const uint32_t g1_k2_x[12] = {
    0x58a9ba3c, 0x53e978ce, 0x4f3d65f9, 0x3ea0583c,
    0xf0012960, 0x4d20bb47, 0xe5b2b5d9, 0xa54c664a,
    0x9d7eb21f, 0x26b552a3, 0x26e68785, 0x0008895d
};
static const uint32_t g1_k2_y[12] = {
    0x98293940, 0x70110b32, 0x3f1f6afc, 0xda33c539,
    0x6a5aa785, 0xb86edfd1, 0xe7b1c895, 0xaec6d1c9,
    0x22d11720, 0x25cfc2b5, 0xf8d09b15, 0x06361c83
};

/* g1_k3: k = 0x3 */
static const uint32_t g1_k3_k[8] = {
    0x00000003, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000
};
static const uint32_t g1_k3_x[12] = {
    0x3ee09382, 0xce80364b, 0x3a6e0766, 0x7e4e721b,
    0xf74a07e0, 0xcf259a9e, 0x52ff79d0, 0x73d0b400,
    0xb30bedba, 0x6c6b6546, 0x415708a0, 0x10be1306
};
static const uint32_t g1_k3_y[12] = {
    0x150c5168, 0xf17a411f, 0x0093dd51, 0xd6915159,
    0xf1ae7249, 0xad710783, 0xd3eb6169, 0xe123a127,
    0x3c9c21a1, 0x2dc6f6f5, 0xd0a15a39, 0x16389a58
};

/* g1_k_small: k = 0xdeadbeef */
static const uint32_t g1_k_small_k[8] = {
    0xdeadbeef, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000
};
static const uint32_t g1_k_small_x[12] = {
    0x3b9c24c3, 0x2d4e7c76, 0xaf710d95, 0x6035b02e,
    0xd303d4d4, 0xc92f0a0b, 0x6abbb88b, 0x316cb591,
    0xba1854ea, 0xae0121dc, 0x07d3845f, 0x1236cd91
};
static const uint32_t g1_k_small_y[12] = {
    0xa387024c, 0x65bebd47, 0x16bbe53d, 0xb6eacdb5,
    0x7bea0c5f, 0xee1fdf47, 0xf5d1f181, 0x6661e173,
    0x70ee8dfc, 0x55279842, 0x594d33d4, 0x0157b15d
};

/* g1_k_med: k = 0x123456789abcdef0deadbeef */
static const uint32_t g1_k_med_k[8] = {
    0xdeadbeef, 0x9abcdef0, 0x12345678, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000
};
static const uint32_t g1_k_med_x[12] = {
    0x9d475a4d, 0x1b18eb53, 0xd8f6e1ce, 0xe6236f8d,
    0x31b6309d, 0xefb598f4, 0x204a8fa0, 0x36cbb78e,
    0xf47d0cec, 0x5e56d3fa, 0xa5be2e36, 0x1621eed5
};
static const uint32_t g1_k_med_y[12] = {
    0x9294e86b, 0x5a6821ee, 0x1b2fed11, 0x2462928a,
    0x71e80fe3, 0xa45fb527, 0x94ed6d82, 0x2f3328a4,
    0x094e7aa7, 0x1240e412, 0x4485a273, 0x00625d0f
};

/* g1_k_big: k = 0x11dc60f4392456de3eb13b9046685257bdd640fb06671ad11c80317fa3b1799d */
static const uint32_t g1_k_big_k[8] = {
    0xa3b1799d, 0x1c80317f, 0x06671ad1, 0xbdd640fb,
    0x46685257, 0x3eb13b90, 0x392456de, 0x11dc60f4
};
static const uint32_t g1_k_big_x[12] = {
    0x80accba8, 0x1b60a882, 0xd128950e, 0xbb20729c,
    0x94994795, 0x84f34818, 0xc1278450, 0xbec380a8,
    0xc89d448e, 0xbed7a62e, 0xb8d78b8d, 0x13e29e4e
};
static const uint32_t g1_k_big_y[12] = {
    0x65871c52, 0x28c2aff9, 0x7583bfb9, 0x841738da,
    0x23c2e69d, 0x3844b279, 0xe0c3ce21, 0xb11b5006,
    0x3023b9a4, 0x7cb81e03, 0x09afc1e8, 0x09a3d1bc
};

/* g1_k_big2: k = 0x4b95423416419f828b9d2434e465e150bd9c66b3ad3c2d6d1a3d1fa7bc8960a9 */
static const uint32_t g1_k_big2_k[8] = {
    0xbc8960a9, 0x1a3d1fa7, 0xad3c2d6d, 0xbd9c66b3,
    0xe465e150, 0x8b9d2434, 0x16419f82, 0x4b954234
};
static const uint32_t g1_k_big2_x[12] = {
    0x77d3fc6b, 0x7aa20caa, 0xa744b1bd, 0x6f68a128,
    0x7c9a555f, 0x34eecaa2, 0xd4f742a6, 0xae003368,
    0xe969a53a, 0xf4577550, 0x90b2f158, 0x0e6c6325
};
static const uint32_t g1_k_big2_y[12] = {
    0xb83282c8, 0xbada4649, 0x129facba, 0x8426845c,
    0x313ac73c, 0xd5e8fa39, 0xcf8640f6, 0x5a93f13b,
    0xd5b23d73, 0x3248dd19, 0x77b2f86c, 0x06d131b7
};

/* G1 iteration table */
typedef struct {
    const char *name;
    const uint32_t *k;
    const uint32_t *x;
    const uint32_t *y;
    int nbits;
} g1_test_vec_t;

static const g1_test_vec_t G1_TEST_VECTORS[NUM_G1_TEST_VECTORS] = {
    {"g1_k1", g1_k1_k, g1_k1_x, g1_k1_y, 1},
    {"g1_k2", g1_k2_k, g1_k2_x, g1_k2_y, 2},
    {"g1_k3", g1_k3_k, g1_k3_x, g1_k3_y, 2},
    {"g1_k_small", g1_k_small_k, g1_k_small_x, g1_k_small_y, 32},
    {"g1_k_med", g1_k_med_k, g1_k_med_x, g1_k_med_y, 93},
    {"g1_k_big", g1_k_big_k, g1_k_big_x, g1_k_big_y, 253},
    {"g1_k_big2", g1_k_big2_k, g1_k_big2_x, g1_k_big2_y, 255},
};

/* ===== G2 test vectors ===== */

/* g2_k1: k = 0x1 */
static const uint32_t g2_k1_k[8] = {
    0x00000001, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000
};
static const uint32_t g2_k1_x_c0[12] = {
    0x02940a10, 0xf5f28fa2, 0x87b4961a, 0xb3f5fb26,
    0x3e2ae580, 0xa1a893b5, 0x1a3caee9, 0x9894999d,
    0x1863366b, 0x6f67b763, 0x4350bcd7, 0x05819192
};
static const uint32_t g2_k1_x_c1[12] = {
    0x9e23f606, 0xa5a9c075, 0xbccd60c3, 0xaaa0c59d,
    0xe2867806, 0x3bb17e18, 0x8541b367, 0x1b1ab6cc,
    0xf2158547, 0xc2b6ed0e, 0x7360edf3, 0x11922a09
};
static const uint32_t g2_k1_y_c0[12] = {
    0x60494c4a, 0x4c730af8, 0x5e369c5a, 0x597cfa1f,
    0xaa0a635a, 0xe7e6856c, 0x6e0d495f, 0xbbefb5e9,
    0xf0ef25a2, 0x07d3a975, 0x7e80dae5, 0x0083fd8e
};
static const uint32_t g2_k1_y_c1[12] = {
    0xdf64b05d, 0xadc0fc92, 0x2b1461dc, 0x18aa270a,
    0x3be4eba0, 0x86adac6a, 0xc93da33a, 0x79495c4e,
    0xa43ccaed, 0xe7175850, 0x63de1bf2, 0x0b2bc2a1
};

/* g2_k2: k = 0x2 */
static const uint32_t g2_k2_k[8] = {
    0x00000002, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000
};
static const uint32_t g2_k2_x_c0[12] = {
    0x9620f98b, 0xe9d9e2da, 0x46b97f36, 0x54f11993,
    0x376bed27, 0x3db3b820, 0xb0b64f4c, 0xcfdb31c9,
    0x86354493, 0x41d7c127, 0xc255c064, 0x05710794
};
static const uint32_t g2_k2_x_c1[12] = {
    0x6ea0d06e, 0xd6c1d3ca, 0x5595489f, 0xda0cbd90,
    0x3479221d, 0x4f5352d4, 0x6f8c97e0, 0x8ade5d73,
    0x925ef70e, 0x48cc8433, 0xea91ef81, 0x08d7ea71
};
static const uint32_t g2_k2_y_c0[12] = {
    0x4b0d186f, 0x15ba26eb, 0xb7e9e01e, 0x0d086d64,
    0x652f4c78, 0xc8b848dd, 0x123bae4f, 0xeecf46a6,
    0xb6dc812a, 0x255e8dd8, 0x21dcf93f, 0x164142af
};
static const uint32_t g2_k2_y_c1[12] = {
    0x95984db4, 0xf9b4a1a8, 0xcccff748, 0xd417b114,
    0xc89f086e, 0x6856301f, 0x8931e3da, 0x41c77787,
    0x066a2105, 0x3556b155, 0x25cb89cf, 0x00acf7d3
};

/* g2_k3: k = 0x3 */
static const uint32_t g2_k3_k[8] = {
    0x00000003, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000
};
static const uint32_t g2_k3_x_c0[12] = {
    0x5ddaa0e6, 0xa7052b22, 0xf6a42f18, 0x9ae6765c,
    0xd8c474c7, 0xaef3a6c4, 0xebb0cd2d, 0xf78fce2c,
    0xe3db77bb, 0x36245356, 0x7bc7e26b, 0x0ba3b3bb
};
static const uint32_t g2_k3_x_c1[12] = {
    0xc596e547, 0xa1150240, 0xc62b58a6, 0x3c80605f,
    0x3ae2f892, 0xdd83829c, 0xd35abf91, 0x6c8fde96,
    0x6f372cb7, 0xe5d4dd42, 0xdf260527, 0x03a2eed1
};
static const uint32_t g2_k3_y_c0[12] = {
    0xb1be4d05, 0xc4eb9556, 0x9076080c, 0x8ab4f730,
    0xe1ded3fe, 0xef307b27, 0x0e50426a, 0x5036695a,
    0x17c645d1, 0x233ee461, 0x1c58676f, 0x17c4c975
};
static const uint32_t g2_k3_y_c1[12] = {
    0xce1e28b9, 0xef9b0c1d, 0x21755e8a, 0x6a54a2c1,
    0xbc513c0d, 0xd331c2fa, 0x549ca4f7, 0x20a8ff08,
    0xc421d43f, 0x8afa134b, 0x584150ee, 0x17eec916
};

/* g2_k_small: k = 0xfeedface */
static const uint32_t g2_k_small_k[8] = {
    0xfeedface, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000
};
static const uint32_t g2_k_small_x_c0[12] = {
    0xd18b7487, 0x2242ccff, 0x5c41df7f, 0x94a2024b,
    0x9a3b1ef0, 0x61ecbe2a, 0x145120a8, 0xff99d6a2,
    0xf2de4283, 0xdbc19e44, 0x49f02698, 0x0b8be0d3
};
static const uint32_t g2_k_small_x_c1[12] = {
    0xa2989ddf, 0x9e2f9447, 0xfd0f474d, 0x4ec6c7ec,
    0xec2bb7ab, 0x004634ea, 0x34f03d47, 0x7b5fc3a7,
    0x3a4d3516, 0xb7c13e9d, 0x385ee70a, 0x1471234c
};
static const uint32_t g2_k_small_y_c0[12] = {
    0xfbbf9f00, 0xe259cfda, 0x9a8d0b59, 0x8b6d453f,
    0x8e9d11ff, 0xaf9a008a, 0xf25490b1, 0x7cfbf1c1,
    0xf950505a, 0xf942ef5a, 0xdb2a01dd, 0x16bd453e
};
static const uint32_t g2_k_small_y_c1[12] = {
    0x072a6682, 0x9fe163c7, 0x1dd81a2b, 0xeee9c33e,
    0xd53e2650, 0x4a7577bd, 0x8ae59855, 0x2c57c5cc,
    0x237e974c, 0xe516e2c0, 0xcbe23eff, 0x06355632
};

/* g2_k_med: k = 0xabcdef0123456789cafebabe */
static const uint32_t g2_k_med_k[8] = {
    0xcafebabe, 0x23456789, 0xabcdef01, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000
};
static const uint32_t g2_k_med_x_c0[12] = {
    0x9598d9d3, 0x0b62cbc1, 0xbfc7c196, 0x682b6636,
    0x79c32167, 0xf8e4bed7, 0x6e4f2ea0, 0x49834b3f,
    0x84ef2da3, 0x26bf274c, 0x19747ee3, 0x1420deb7
};
static const uint32_t g2_k_med_x_c1[12] = {
    0x1b4efc69, 0x54bd1a68, 0xbd88798b, 0x5247c18d,
    0xb62bc97b, 0xdc4b52fe, 0x65cf5dc5, 0xc61d472a,
    0xdb443313, 0x4df206f0, 0x55756f70, 0x10f3863e
};
static const uint32_t g2_k_med_y_c0[12] = {
    0x00a53915, 0x5a62c79d, 0x10e2bbf8, 0x4002e1fb,
    0x532fcce2, 0xc379be66, 0xad448461, 0x0d31c6e9,
    0xe4d16707, 0xf003559f, 0xef0967fe, 0x0140c337
};
static const uint32_t g2_k_med_y_c1[12] = {
    0x245ba4b1, 0xc09d5798, 0xc8909567, 0x15ab686e,
    0xada197b5, 0xba4cdefc, 0x1c374b35, 0x5575ab1f,
    0xfbdd81cf, 0x9c049a5a, 0x6bfd75d6, 0x0d9cbfb4
};

/* g2_k_big: k = 0x4d0ef322815ef6d13b8faa1837f8a88b17fc695a07a0ca6e0822e8f36c031199 */
static const uint32_t g2_k_big_k[8] = {
    0x6c031199, 0x0822e8f3, 0x07a0ca6e, 0x17fc695a,
    0x37f8a88b, 0x3b8faa18, 0x815ef6d1, 0x4d0ef322
};
static const uint32_t g2_k_big_x_c0[12] = {
    0x563c7558, 0xf87861d0, 0x5fdc19b5, 0x8fc871ba,
    0x565be471, 0xe01fd57a, 0x40192a33, 0x645fb16c,
    0x862beebd, 0x4da150e0, 0x8a825e28, 0x0e4ceef9
};
static const uint32_t g2_k_big_x_c1[12] = {
    0xf7945233, 0x34365bd0, 0xaec130ba, 0x59437bae,
    0xb674d993, 0x8d73ee8f, 0xd5878d21, 0x0d2246b4,
    0xf77b2900, 0xc49bbe32, 0x1785a573, 0x15844a82
};
static const uint32_t g2_k_big_y_c0[12] = {
    0xbc25c620, 0xe54554d8, 0x429bd598, 0x3bc01364,
    0x41d34e2e, 0x4662ba99, 0xd64a65f0, 0xb40bb472,
    0x0f8cbf9e, 0xc311b4bd, 0xc584b16a, 0x0dbd4d9b
};
static const uint32_t g2_k_big_y_c1[12] = {
    0x736639ef, 0xa5206c98, 0xd942a8cb, 0xdc5a2a33,
    0x8ba903fb, 0xf846fa90, 0x51a82be7, 0xa9e8a021,
    0x939dee1a, 0x8c18ef58, 0x92b211e8, 0x14c09c64
};

/* g2_k_big2: k = 0x35b2d3528b8148f6b38a088ca65ed389b74d0fb132e706298fadc1a606cb0fb3 */
static const uint32_t g2_k_big2_k[8] = {
    0x06cb0fb3, 0x8fadc1a6, 0x32e70629, 0xb74d0fb1,
    0xa65ed389, 0xb38a088c, 0x8b8148f6, 0x35b2d352
};
static const uint32_t g2_k_big2_x_c0[12] = {
    0xdeee6fb2, 0x11817c2c, 0xfda9ea6c, 0x7672f430,
    0x5702174c, 0xacb558ac, 0x424bfe88, 0x6400e770,
    0xd88820d7, 0xc4d499d4, 0x35c5a1e1, 0x115562cc
};
static const uint32_t g2_k_big2_x_c1[12] = {
    0xbb58c778, 0xa06a736a, 0x0ded5c40, 0xed2e2ee1,
    0x6828437b, 0xff481f0b, 0x8fa9b8ba, 0xf93ab47b,
    0x95786b65, 0x0c453d87, 0x4d2ffe6e, 0x17dce3be
};
static const uint32_t g2_k_big2_y_c0[12] = {
    0xd00f9496, 0x05fc3cf8, 0xc0e0f962, 0x67970838,
    0x52b97372, 0xd59a8be8, 0x4d97920c, 0x70799db6,
    0xcb2ad1ec, 0x66ccbc0f, 0xecc00143, 0x08e5ed0e
};
static const uint32_t g2_k_big2_y_c1[12] = {
    0x5acd3c7e, 0x2ef75b84, 0xba984267, 0x8f1d2902,
    0xaf93c75c, 0x4a905bea, 0x0daf5880, 0x786a0223,
    0xd6dbc4d8, 0x831ad787, 0x54168d7a, 0x051305e4
};

/* G2 iteration table */
typedef struct {
    const char *name;
    const uint32_t *k;
    const uint32_t *x_c0;
    const uint32_t *x_c1;
    const uint32_t *y_c0;
    const uint32_t *y_c1;
    int nbits;
} g2_test_vec_t;

static const g2_test_vec_t G2_TEST_VECTORS[NUM_G2_TEST_VECTORS] = {
    {"g2_k1", g2_k1_k, g2_k1_x_c0, g2_k1_x_c1, g2_k1_y_c0, g2_k1_y_c1, 1},
    {"g2_k2", g2_k2_k, g2_k2_x_c0, g2_k2_x_c1, g2_k2_y_c0, g2_k2_y_c1, 2},
    {"g2_k3", g2_k3_k, g2_k3_x_c0, g2_k3_x_c1, g2_k3_y_c0, g2_k3_y_c1, 2},
    {"g2_k_small", g2_k_small_k, g2_k_small_x_c0, g2_k_small_x_c1, g2_k_small_y_c0, g2_k_small_y_c1, 32},
    {"g2_k_med", g2_k_med_k, g2_k_med_x_c0, g2_k_med_x_c1, g2_k_med_y_c0, g2_k_med_y_c1, 96},
    {"g2_k_big", g2_k_big_k, g2_k_big_x_c0, g2_k_big_x_c1, g2_k_big_y_c0, g2_k_big_y_c1, 255},
    {"g2_k_big2", g2_k_big2_k, g2_k_big2_x_c0, g2_k_big2_x_c1, g2_k_big2_y_c0, g2_k_big2_y_c1, 254},
};
