#!/usr/bin/env python3
"""
gen_test_vectors.py — generate C test vectors for Fp operations.
"""

import os
import sys
import random

# Ensure we can import fp_reference regardless of cwd
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

from fp_reference import (
    P, N_LIMBS, R, to_limbs, to_mont, from_mont,
    fp_add, fp_sub, fp_mul_mont, format_limbs_c
)

random.seed(42)

NUM_RANDOM = 20

def emit_pair(prefix: str, a: int, b: int):
    a_mont = to_mont(a)
    b_mont = to_mont(b)
    a_plain = a  # the plain integer value (NOT in Mont form)
    sum_plain = fp_add(a, b)
    sum_mont = to_mont(sum_plain)
    diff_plain = fp_sub(a, b)
    diff_mont = to_mont(diff_plain)
    prod_plain = (a * b) % P
    prod_mont = to_mont(prod_plain)
    # New for Phase C
    sqr_plain = (a * a) % P
    sqr_mont = to_mont(sqr_plain)
    # Inverse: only if a != 0
    if a != 0:
        inv_plain = pow(a, P-2, P)
        inv_mont = to_mont(inv_plain)
    else:
        inv_plain = 0
        inv_mont = 0

    lines = []
    lines.append(f"/* {prefix}: a={hex(a)[:18]}..., b={hex(b)[:18]}... */")
    lines.append(format_limbs_c(f"{prefix}_a_mont", a_mont))
    lines.append(format_limbs_c(f"{prefix}_a_plain", a_plain))
    lines.append(format_limbs_c(f"{prefix}_b_mont", b_mont))
    lines.append(format_limbs_c(f"{prefix}_sum_mont", sum_mont))
    lines.append(format_limbs_c(f"{prefix}_diff_mont", diff_mont))
    lines.append(format_limbs_c(f"{prefix}_prod_mont", prod_mont))
    lines.append(format_limbs_c(f"{prefix}_sqr_mont", sqr_mont))
    lines.append(format_limbs_c(f"{prefix}_inv_mont", inv_mont))
    lines.append("")
    return "\n".join(lines)


edge_cases = [
    ("zero_zero",         0, 0),
    ("one_one",           1, 1),
    ("zero_one",          0, 1),
    ("p_minus_1_1",       P-1, 1),
    ("p_minus_1_p_minus_1", P-1, P-1),
    ("one_p_minus_1",     1, P-1),
]

random_cases = [
    (f"rand_{i:02d}", random.randrange(P), random.randrange(P))
    for i in range(NUM_RANDOM)
]

all_cases = edge_cases + random_cases

out = []
out.append("/* AUTO-GENERATED by tools/bls12_381_port/gen_test_vectors.py */")
out.append("/* Do not edit manually -- re-run the generator instead.    */")
out.append("#pragma once")
out.append("#include <stdint.h>")
out.append("")
out.append(f"#define NUM_TEST_VECTORS {len(all_cases)}")
out.append("")

for name, a, b in all_cases:
    out.append(emit_pair(name, a, b))

out.append("typedef struct {")
out.append("    const char *name;")
out.append("    const uint32_t *a_mont;")
out.append("    const uint32_t *a_plain;")
out.append("    const uint32_t *b_mont;")
out.append("    const uint32_t *sum_mont;")
out.append("    const uint32_t *diff_mont;")
out.append("    const uint32_t *prod_mont;")
out.append("    const uint32_t *sqr_mont;")
out.append("    const uint32_t *inv_mont;")
out.append("    int a_is_zero;")
out.append("} fp_test_vec_t;")
out.append("")
out.append("static const fp_test_vec_t FP_TEST_VECTORS[NUM_TEST_VECTORS] = {")
for name, a, _ in all_cases:
    is_zero = 1 if a == 0 else 0
    out.append(f'    {{"{name}", {name}_a_mont, {name}_a_plain, {name}_b_mont, {name}_sum_mont, {name}_diff_mont, {name}_prod_mont, {name}_sqr_mont, {name}_inv_mont, {is_zero}}},')
out.append("};")

# Write to script-relative path
output_path = os.path.join(SCRIPT_DIR, "fp_test_vectors.h")
with open(output_path, "w") as f:
    f.write("\n".join(out))

print(f"OK Generated {len(all_cases)} test vectors")
print(f"   Edge cases:   {len(edge_cases)}")
print(f"   Random cases: {len(random_cases)}")
print(f"OK Wrote {output_path}")
