#!/usr/bin/env python3
"""
gen_g_test_vectors.py — generate test vectors for g1 and g2 using py_ecc.

For G1 (and G2) we test:
  1. Generator validity (already constants — just sanity)
  2. k * G for several k values (compare C vs Python)
  3. 2*G = G + G  (doubling consistency)
  4. q*G = infinity  (group order)
"""

import os
import sys
import random
import secrets

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

from fp_reference import P, to_mont, to_limbs

from py_ecc.bls12_381 import G1, G2, multiply, add, neg
from py_ecc.bls12_381 import FQ, FQ2

# Curve order q
Q = 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001

random.seed(42)

def fq_to_int(x):
    """Extract int from FQ or FQ2 element."""
    if hasattr(x, 'n'):  # FQ
        return int(x.n)
    return None

def fq2_to_pair(x):
    """FQ2 -> (c0, c1) plain ints."""
    return (int(x.coeffs[0]), int(x.coeffs[1]))


def format_fp_array(name, value_plain):
    """Format Fp value (plain int) as 12-limb uint32_t array in Mont form."""
    mont = to_mont(value_plain)
    limbs = to_limbs(mont)
    lines = [f"static const uint32_t {name}[12] = {{"]
    for i in range(0, 12, 4):
        chunk = limbs[i:i+4]
        line = "    " + ", ".join(f"0x{l:08x}" for l in chunk)
        if i + 4 < 12:
            line += ","
        lines.append(line)
    lines.append("};")
    return "\n".join(lines)


def format_fp_plain_array(name, value_plain):
    """Format Fp value as 12-limb little-endian uint32_t array (plain, NOT Montgomery)."""
    limbs = to_limbs(value_plain)
    lines = [f"static const uint32_t {name}[12] = {{"]
    for i in range(0, 12, 4):
        chunk = limbs[i:i+4]
        line = "    " + ", ".join(f"0x{l:08x}" for l in chunk)
        if i + 4 < 12:
            line += ","
        lines.append(line)
    lines.append("};")
    return "\n".join(lines)


def scalar_to_limbs_8(k):
    """Convert scalar k (255-bit BLS12-381 scalar) to 8 × uint32_t LE limbs."""
    return [(k >> (32*i)) & 0xFFFFFFFF for i in range(8)]


def emit_g1_test(name, k):
    """Compute k*G1 and emit (k as 8 limbs, k*G1 affine in Mont form)."""
    point = multiply(G1, k)
    if point is None:  # infinity
        return None, None
    
    x = fq_to_int(point[0])
    y = fq_to_int(point[1])
    
    k_limbs = scalar_to_limbs_8(k)
    
    lines = []
    lines.append(f"/* {name}: k = 0x{k:x} */")
    lines.append(f"static const uint32_t {name}_k[8] = {{")
    for i in range(0, 8, 4):
        chunk = k_limbs[i:i+4]
        line = "    " + ", ".join(f"0x{l:08x}" for l in chunk)
        if i + 4 < 8:
            line += ","
        lines.append(line)
    lines.append("};")
    
    lines.append(format_fp_array(f"{name}_x", x))     # Mont form
    lines.append(format_fp_array(f"{name}_y", y))     # Mont form
    lines.append("")
    return "\n".join(lines), len(lines)


def emit_g2_test(name, k):
    """Compute k*G2 and emit results."""
    point = multiply(G2, k)
    if point is None:
        return None
    
    x_c0, x_c1 = fq2_to_pair(point[0])
    y_c0, y_c1 = fq2_to_pair(point[1])
    
    k_limbs = scalar_to_limbs_8(k)
    
    lines = []
    lines.append(f"/* {name}: k = 0x{k:x} */")
    lines.append(f"static const uint32_t {name}_k[8] = {{")
    for i in range(0, 8, 4):
        chunk = k_limbs[i:i+4]
        line = "    " + ", ".join(f"0x{l:08x}" for l in chunk)
        if i + 4 < 8:
            line += ","
        lines.append(line)
    lines.append("};")
    
    lines.append(format_fp_array(f"{name}_x_c0", x_c0))
    lines.append(format_fp_array(f"{name}_x_c1", x_c1))
    lines.append(format_fp_array(f"{name}_y_c0", y_c0))
    lines.append(format_fp_array(f"{name}_y_c1", y_c1))
    lines.append("")
    return "\n".join(lines)


# Define scalars to test
g1_scalars = [
    ("g1_k1",     1),                          # G itself
    ("g1_k2",     2),                          # 2*G
    ("g1_k3",     3),                          # 3*G
    ("g1_k_small", 0xdeadbeef),                # small random
    ("g1_k_med",  0x123456789abcdef0deadbeef), # medium
    ("g1_k_big",  random.randrange(Q)),        # full-scale random
    ("g1_k_big2", random.randrange(Q)),        # another random
]

g2_scalars = [
    ("g2_k1",     1),
    ("g2_k2",     2),
    ("g2_k3",     3),
    ("g2_k_small", 0xfeedface),
    ("g2_k_med",  0xabcdef0123456789cafebabe),
    ("g2_k_big",  random.randrange(Q)),
    ("g2_k_big2", random.randrange(Q)),
]


# Generate the test vector header
out = []
out.append("/* AUTO-GENERATED by tools/bls12_381_port/gen_g_test_vectors.py */")
out.append("/* Tests g1_scalar_mul and g2_scalar_mul against py_ecc.       */")
out.append("#pragma once")
out.append("#include <stdint.h>")
out.append("")

out.append(f"#define NUM_G1_TEST_VECTORS {len(g1_scalars)}")
out.append(f"#define NUM_G2_TEST_VECTORS {len(g2_scalars)}")
out.append("")

# Curve order q (for the q*G = inf test)
out.append("/* Scalar field order q (in 8 little-endian uint32_t limbs) */")
q_limbs = scalar_to_limbs_8(Q)
out.append("static const uint32_t BLS_Q_8LIMB[8] = {")
for i in range(0, 8, 4):
    chunk = q_limbs[i:i+4]
    line = "    " + ", ".join(f"0x{l:08x}" for l in chunk)
    if i + 4 < 8:
        line += ","
    out.append(line)
out.append("};")
out.append("")

out.append("/* ===== G1 test vectors ===== */")
out.append("")
for name, k in g1_scalars:
    text, _ = emit_g1_test(name, k)
    out.append(text)

out.append("/* G1 iteration table */")
out.append("typedef struct {")
out.append("    const char *name;")
out.append("    const uint32_t *k;")
out.append("    const uint32_t *x;")
out.append("    const uint32_t *y;")
out.append("    int nbits;")
out.append("} g1_test_vec_t;")
out.append("")
out.append("static const g1_test_vec_t G1_TEST_VECTORS[NUM_G1_TEST_VECTORS] = {")
for name, k in g1_scalars:
    nbits = max(k.bit_length(), 1)
    out.append(f'    {{"{name}", {name}_k, {name}_x, {name}_y, {nbits}}},')
out.append("};")
out.append("")

out.append("/* ===== G2 test vectors ===== */")
out.append("")
for name, k in g2_scalars:
    out.append(emit_g2_test(name, k))

out.append("/* G2 iteration table */")
out.append("typedef struct {")
out.append("    const char *name;")
out.append("    const uint32_t *k;")
out.append("    const uint32_t *x_c0;")
out.append("    const uint32_t *x_c1;")
out.append("    const uint32_t *y_c0;")
out.append("    const uint32_t *y_c1;")
out.append("    int nbits;")
out.append("} g2_test_vec_t;")
out.append("")
out.append("static const g2_test_vec_t G2_TEST_VECTORS[NUM_G2_TEST_VECTORS] = {")
for name, k in g2_scalars:
    nbits = max(k.bit_length(), 1)
    out.append(f'    {{"{name}", {name}_k, {name}_x_c0, {name}_x_c1, {name}_y_c0, {name}_y_c1, {nbits}}},')
out.append("};")
out.append("")

output_path = os.path.join(SCRIPT_DIR, "g_test_vectors.h")
with open(output_path, "w") as f:
    f.write("\n".join(out))

print(f"OK Generated G1 vectors: {len(g1_scalars)}")
print(f"OK Generated G2 vectors: {len(g2_scalars)}")
print(f"OK Wrote {output_path}")
