#!/usr/bin/env python3
"""Generate test vectors for fp2.c — output to fp2_test_vectors.h"""

import os
import sys
import random

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

from fp_reference import P, to_limbs
from fp2_reference import (
    fp2_add, fp2_sub, fp2_mul, fp2_sqr, fp2_inv, fp2_mul_xi,
    to_mont_fp2, format_fp2_c
)

random.seed(42)
NUM_RANDOM = 15


def emit_pair(prefix, a, b):
    """Emit test data for one (a, b) pair."""
    a_mont = to_mont_fp2(a)
    b_mont = to_mont_fp2(b)
    sum_mont   = to_mont_fp2(fp2_add(a, b))
    diff_mont  = to_mont_fp2(fp2_sub(a, b))
    prod_mont  = to_mont_fp2(fp2_mul(a, b))
    sqr_a_mont = to_mont_fp2(fp2_sqr(a))
    xi_a_mont  = to_mont_fp2(fp2_mul_xi(a))
    if a != (0, 0):
        inv_a_mont = to_mont_fp2(fp2_inv(a))
    else:
        inv_a_mont = (0, 0)

    lines = []
    lines.append(f"/* {prefix}: a=({hex(a[0])[:14]}..., {hex(a[1])[:14]}...), "
                 f"b=({hex(b[0])[:14]}..., {hex(b[1])[:14]}...) */")
    lines.append(format_fp2_c(f"{prefix}_a_mont",    a_mont))
    lines.append(format_fp2_c(f"{prefix}_b_mont",    b_mont))
    lines.append(format_fp2_c(f"{prefix}_sum_mont",  sum_mont))
    lines.append(format_fp2_c(f"{prefix}_diff_mont", diff_mont))
    lines.append(format_fp2_c(f"{prefix}_prod_mont", prod_mont))
    lines.append(format_fp2_c(f"{prefix}_sqr_mont",  sqr_a_mont))
    lines.append(format_fp2_c(f"{prefix}_inv_mont",  inv_a_mont))
    lines.append(format_fp2_c(f"{prefix}_xi_mont",   xi_a_mont))
    lines.append("")
    return "\n".join(lines)


# Edge cases
edge_cases = [
    ("zero",         (0, 0),       (0, 0)),
    ("one",          (1, 0),       (1, 0)),
    ("u",            (0, 1),       (0, 1)),     # the imaginary unit
    ("one_plus_u",   (1, 1),       (1, 1)),     # this is xi itself
    ("u_squared",    (0, 1),       (0, 1)),     # u*u = -1
]

# Random cases
random_cases = [
    (f"rand_{i:02d}",
     (random.randrange(P), random.randrange(P)),
     (random.randrange(P), random.randrange(P)))
    for i in range(NUM_RANDOM)
]

all_cases = edge_cases + random_cases

out = []
out.append("/* AUTO-GENERATED by tools/bls12_381_port/gen_fp2_test_vectors.py */")
out.append("/* Do not edit manually -- re-run the generator instead.        */")
out.append("#pragma once")
out.append("#include <stdint.h>")
out.append("")
out.append(f"#define NUM_FP2_TEST_VECTORS {len(all_cases)}")
out.append("")

for name, a, b in all_cases:
    out.append(emit_pair(name, a, b))

# Iteration table
out.append("typedef struct {")
out.append("    const char *name;")
out.append("    const uint32_t *a_c0; const uint32_t *a_c1;")
out.append("    const uint32_t *b_c0; const uint32_t *b_c1;")
out.append("    const uint32_t *sum_c0; const uint32_t *sum_c1;")
out.append("    const uint32_t *diff_c0; const uint32_t *diff_c1;")
out.append("    const uint32_t *prod_c0; const uint32_t *prod_c1;")
out.append("    const uint32_t *sqr_c0; const uint32_t *sqr_c1;")
out.append("    const uint32_t *inv_c0; const uint32_t *inv_c1;")
out.append("    const uint32_t *xi_c0;  const uint32_t *xi_c1;")
out.append("    int a_is_zero;")
out.append("} fp2_test_vec_t;")
out.append("")
out.append("static const fp2_test_vec_t FP2_TEST_VECTORS[NUM_FP2_TEST_VECTORS] = {")
for name, a, _ in all_cases:
    is_zero = 1 if a == (0, 0) else 0
    out.append(
        f'    {{"{name}",'
        f' {name}_a_mont_c0, {name}_a_mont_c1,'
        f' {name}_b_mont_c0, {name}_b_mont_c1,'
        f' {name}_sum_mont_c0, {name}_sum_mont_c1,'
        f' {name}_diff_mont_c0, {name}_diff_mont_c1,'
        f' {name}_prod_mont_c0, {name}_prod_mont_c1,'
        f' {name}_sqr_mont_c0, {name}_sqr_mont_c1,'
        f' {name}_inv_mont_c0, {name}_inv_mont_c1,'
        f' {name}_xi_mont_c0, {name}_xi_mont_c1,'
        f' {is_zero}}},'
    )
out.append("};")

output_path = os.path.join(SCRIPT_DIR, "fp2_test_vectors.h")
with open(output_path, "w") as f:
    f.write("\n".join(out))

print(f"OK Generated {len(all_cases)} fp2 test vectors")
print(f"   Edge cases: {len(edge_cases)}, Random: {len(random_cases)}")
print(f"OK Wrote {output_path}")
