#!/usr/bin/env python3
"""
gen_fp12_test_vectors.py — generate Fp¹² test vectors using py_ecc as ground truth.

Operations tested:
  fp12_mul, fp12_sqr, fp12_eq, fp12_zero, fp12_one
  bytes round-trip (576 bytes for BLS12-381)

Format:
  Each vector has: a (12 coeffs), b (12 coeffs),
                   product (12 coeffs), squared_a (12 coeffs)
  Each coefficient is in Montgomery form on the C side, plain on Python side.
  We emit Mont form so the C tests can load directly.
"""

import os
import sys
import random

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

from fp_reference import P, to_mont, to_limbs

from py_ecc.bls12_381 import FQ12

random.seed(42)
NUM_RANDOM = 8

def random_fq12_plain():
    """Random Fp12 element — return tuple of 12 Fp coefficients (plain ints)."""
    return tuple(random.randrange(P) for _ in range(12))

def fq12_mul_plain(a, b):
    """Multiply via py_ecc, return 12-tuple."""
    fa = FQ12(list(a))
    fb = FQ12(list(b))
    prod = fa * fb
    return tuple(int(c) for c in prod.coeffs)

def fq12_sqr_plain(a):
    fa = FQ12(list(a))
    sq = fa * fa
    return tuple(int(c) for c in sq.coeffs)

def fq12_to_mont(coeffs):
    """Convert 12-tuple of plain ints to 12-tuple of Mont ints."""
    return tuple(to_mont(c) for c in coeffs)

def format_fp12_c(name, coeffs_mont):
    """Format Fp12 element as 12 separate uint32_t arrays + a flat list."""
    lines = []
    for i, c in enumerate(coeffs_mont):
        limbs = to_limbs(c)
        var = f"{name}_c{i}"
        lines.append(f"static const uint32_t {var}[12] = {{")
        for j in range(0, 12, 4):
            chunk = limbs[j:j+4]
            line = "    " + ", ".join(f"0x{l:08x}" for l in chunk)
            if j + 4 < 12:
                line += ","
            lines.append(line)
        lines.append("};")
    return "\n".join(lines)


def emit_vector(prefix, a, b):
    """Emit test data: a, b, prod=a*b, sqr_a=a*a, all in Montgomery form."""
    a_mont = fq12_to_mont(a)
    b_mont = fq12_to_mont(b)
    prod = fq12_mul_plain(a, b)
    prod_mont = fq12_to_mont(prod)
    sqr_a = fq12_sqr_plain(a)
    sqr_a_mont = fq12_to_mont(sqr_a)

    lines = []
    lines.append(f"/* {prefix}: 12 coefficients each */")
    lines.append(format_fp12_c(f"{prefix}_a", a_mont))
    lines.append(format_fp12_c(f"{prefix}_b", b_mont))
    lines.append(format_fp12_c(f"{prefix}_prod", prod_mont))
    lines.append(format_fp12_c(f"{prefix}_sqr_a", sqr_a_mont))
    lines.append("")
    return "\n".join(lines)


def emit_struct_entry(prefix):
    """Emit a struct initializer for the iteration table."""
    coords_a    = ", ".join(f"{prefix}_a_c{i}"    for i in range(12))
    coords_b    = ", ".join(f"{prefix}_b_c{i}"    for i in range(12))
    coords_prod = ", ".join(f"{prefix}_prod_c{i}" for i in range(12))
    coords_sqr  = ", ".join(f"{prefix}_sqr_a_c{i}" for i in range(12))
    return (f'    {{"{prefix}",\n'
            f'        {{ {coords_a} }},\n'
            f'        {{ {coords_b} }},\n'
            f'        {{ {coords_prod} }},\n'
            f'        {{ {coords_sqr} }}}}')


# Edge cases
edge_cases = [
    ("one_one",
     (1,0,0,0,0,0,0,0,0,0,0,0),
     (1,0,0,0,0,0,0,0,0,0,0,0)),
    ("one_x",
     (1,0,0,0,0,0,0,0,0,0,0,0),
     (0,1,0,0,0,0,0,0,0,0,0,0)),  # multiply by x
    ("x_x6",
     (0,1,0,0,0,0,0,0,0,0,0,0),
     (0,0,0,0,0,0,1,0,0,0,0,0)),  # x * x^6 = x^7
    ("x6_x6",
     (0,0,0,0,0,0,1,0,0,0,0,0),
     (0,0,0,0,0,0,1,0,0,0,0,0)),  # x^6 * x^6 = x^12 = 2x^6 - 2 (after reduction!)
]

# Random cases
random_cases = [
    (f"rand_{i:02d}", random_fq12_plain(), random_fq12_plain())
    for i in range(NUM_RANDOM)
]

all_cases = edge_cases + random_cases

out = []
out.append("/* AUTO-GENERATED by tools/bls12_381_port/gen_fp12_test_vectors.py */")
out.append("/* Tests fp12_mul and fp12_sqr against py_ecc ground truth.       */")
out.append("#pragma once")
out.append("#include <stdint.h>")
out.append("")
out.append(f"#define NUM_FP12_TEST_VECTORS {len(all_cases)}")
out.append("")

for name, a, b in all_cases:
    out.append(emit_vector(name, a, b))

# Iteration table
out.append("typedef struct {")
out.append("    const char *name;")
out.append("    const uint32_t *a[12];")
out.append("    const uint32_t *b[12];")
out.append("    const uint32_t *prod[12];")
out.append("    const uint32_t *sqr_a[12];")
out.append("} fp12_test_vec_t;")
out.append("")
out.append(f"static const fp12_test_vec_t FP12_TEST_VECTORS[NUM_FP12_TEST_VECTORS] = {{")
for name, _, _ in all_cases:
    out.append(emit_struct_entry(name) + ",")
out.append("};")

output_path = os.path.join(SCRIPT_DIR, "fp12_test_vectors.h")
with open(output_path, "w") as f:
    f.write("\n".join(out))

print(f"OK Generated {len(all_cases)} fp12 test vectors")
print(f"   Edge cases: {len(edge_cases)}")
print(f"   Random:     {len(random_cases)}")
print(f"OK Wrote {output_path}")
