

# This file was *autogenerated* from the file tools/bls12_381_port/gen_test_vectors.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab = Integer(0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab); _sage_const_42 = Integer(42); _sage_const_12 = Integer(12); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_50 = Integer(50); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_30 = Integer(30); _sage_const_20 = Integer(20)#!/usr/bin/env sage
# =============================================================================
#  gen_test_vectors.sage — generate Fp test vectors for the BLS12-381 port
#
#  Outputs: tools/bls12_381_port/fp_test_vectors.txt
#
#  Format (one test per line):
#    OP a_hex b_hex expected_hex
#  
#  OPs:
#    ADD  a b expected   →  a + b mod p
#    SUB  a b expected   →  a - b mod p
#    MUL  a b expected   →  a * b mod p (NOT Montgomery — direct multiplication)
#    SQR  a 0 expected   →  a^2 mod p
#    INV  a 0 expected   →  a^(-1) mod p (Fermat: a^(p-2))
# =============================================================================

import os
import random

# BLS12-381 prime
p = _sage_const_0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab 

# Deterministic random for reproducibility
random.seed(_sage_const_42 )

def hex_for_c(x, n_limbs=_sage_const_12 ):
    """Output as 12-limb hex compatible with our C representation."""
    return f"0x{x:096x}"

def random_fp():
    """Random element in [0, p)."""
    return random.randint(_sage_const_0 , p-_sage_const_1 )

# Generate test vectors
tests = []

# --- ADD tests ---
# Edge cases first, then random
edge_cases_add = [
    (_sage_const_0 , _sage_const_0 ),
    (_sage_const_0 , _sage_const_1 ),
    (_sage_const_1 , _sage_const_0 ),
    (p-_sage_const_1 , _sage_const_1 ),       # wraps to 0
    (p-_sage_const_1 , p-_sage_const_1 ),     # wraps to p-2
    (p//_sage_const_2 , p//_sage_const_2 ),   # half + half
    (p-_sage_const_1 , _sage_const_2 ),       # wraps
]
for a, b in edge_cases_add:
    tests.append(("ADD", a, b, (a + b) % p))

for _ in range(_sage_const_50 ):
    a = random_fp()
    b = random_fp()
    tests.append(("ADD", a, b, (a + b) % p))

# --- SUB tests ---
edge_cases_sub = [
    (_sage_const_0 , _sage_const_0 ),
    (_sage_const_0 , _sage_const_1 ),         # wraps to p-1
    (_sage_const_1 , _sage_const_0 ),
    (p-_sage_const_1 , p-_sage_const_1 ),
    (_sage_const_5 , _sage_const_10 ),        # wraps to p-5
    (p-_sage_const_1 , _sage_const_0 ),
    (_sage_const_0 , p-_sage_const_1 ),       # wraps to 1
]
for a, b in edge_cases_sub:
    tests.append(("SUB", a, b, (a - b) % p))

for _ in range(_sage_const_50 ):
    a = random_fp()
    b = random_fp()
    tests.append(("SUB", a, b, (a - b) % p))

# --- MUL tests ---
edge_cases_mul = [
    (_sage_const_0 , _sage_const_0 ),
    (_sage_const_0 , _sage_const_1 ),
    (_sage_const_1 , _sage_const_1 ),
    (_sage_const_1 , p-_sage_const_1 ),
    (p-_sage_const_1 , p-_sage_const_1 ),
    (_sage_const_2 , p-_sage_const_1 ),
    (p-_sage_const_1 , _sage_const_2 ),
]
for a, b in edge_cases_mul:
    tests.append(("MUL", a, b, (a * b) % p))

for _ in range(_sage_const_50 ):
    a = random_fp()
    b = random_fp()
    tests.append(("MUL", a, b, (a * b) % p))

# --- SQR tests (a*a) ---
edge_cases_sqr = [_sage_const_0 , _sage_const_1 , _sage_const_2 , p-_sage_const_1 , p//_sage_const_2 ]
for a in edge_cases_sqr:
    tests.append(("SQR", a, _sage_const_0 , (a * a) % p))

for _ in range(_sage_const_30 ):
    a = random_fp()
    tests.append(("SQR", a, _sage_const_0 , (a * a) % p))

# --- INV tests (Fermat: a^(p-2)) ---
# Note: cannot invert 0
edge_cases_inv = [_sage_const_1 , _sage_const_2 , p-_sage_const_1 , p//_sage_const_2 ]
for a in edge_cases_inv:
    a_inv = pow(a, p-_sage_const_2 , p)
    tests.append(("INV", a, _sage_const_0 , a_inv))
    # Sanity
    assert (a * a_inv) % p == _sage_const_1 , f"INV verification failed for {a}"

for _ in range(_sage_const_20 ):
    a = random_fp()
    if a == _sage_const_0 :
        continue
    a_inv = pow(a, p-_sage_const_2 , p)
    tests.append(("INV", a, _sage_const_0 , a_inv))
    assert (a * a_inv) % p == _sage_const_1 

# Write to file
out_path = "tools/bls12_381_port/fp_test_vectors.txt"
with open(out_path, "w") as f:
    f.write(f"# Test vectors for BLS12-381 Fp arithmetic\n")
    f.write(f"# Format: OP a_hex b_hex expected_hex\n")
    f.write(f"# All values are PLAIN (not Montgomery)\n")
    f.write(f"# Total tests: {len(tests)}\n")
    f.write(f"\n")
    for op, a, b, expected in tests:
        f.write(f"{op} {hex_for_c(a)} {hex_for_c(b)} {hex_for_c(expected)}\n")

print(f"✓ Generated {len(tests)} test vectors")
print(f"✓ Wrote {out_path}")

# Stats
op_counts = {}
for op, _, _, _ in tests:
    op_counts[op] = op_counts.get(op, _sage_const_0 ) + _sage_const_1 
for op, count in sorted(op_counts.items()):
    print(f"  {op}: {count} tests")

