#pragma once
#include <stdint.h>

/* -----------------------------------------------------------------------
 * BLS12-381 constants in Montgomery form for STM32F407.
 * 
 * All 384-bit values are stored as 12 × uint32_t, little-endian limbs.
 * Montgomery base R = 2^384. All Fp elements are stored as a*R mod p.
 *
 * Curve: y² = x³ + 4 over Fp
 * Twist: y² = x³ + 4(1+u) over Fp² (M-twist)
 * 
 * Generated by tools/bls12_381_port/gen_constants.sage
 * Source: RFC draft-irtf-cfrg-pairing-friendly-curves
 * ----------------------------------------------------------------------- */

#define BLS_FP_LIMBS 12
#define BLS_FP_BITS  381

/* ---- Field prime p (381 bits, in 12 × 32-bit limbs) ---- 
 * p = 0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab
 */
static const uint32_t BLS_P[12] = {
    0xffffaaab,0xb9feffff,0xb153ffff,0x1eabfffe,
    0xf6b0f624,0x6730d2a0,0xf38512bf,0x64774b84,
    0x434bacd7,0x4b1ba7b6,0x397fe69a,0x1a0111ea
};

#define BLS_N0P_FP   0xfffcfffdu   /* -p^(-1) mod 2^32 */

static const uint32_t BLS_R_FP[12] = {   /* R = 2^384 mod p */
    0x0002fffd,0x76090000,0xc40c0002,0xebf4000b,
    0x53c758ba,0x5f489857,0x70525745,0x77ce5853,
    0xa256ec6d,0x5c071a97,0xfa80e493,0x15f65ec3
};

static const uint32_t BLS_R2_FP[12] = {   /* R^2 mod p */
    0x1c341746,0xf4df1f34,0x09d104f1,0x0a76e6a6,
    0x4c95b6d5,0x8de5476c,0x939d83c0,0x67eb88a9,
    0xb519952d,0x9a793e85,0x92cae3aa,0x11988fe5
};

/* ---- Group (scalar) order q (255 bits, in 12 × 32-bit limbs, top 4 unused) ---- 
 * q = 0x0000000000000000000000000000000073eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001
 */
static const uint32_t BLS_Q[12] = {
    0x00000001,0xffffffff,0xfffe5bfe,0x53bda402,
    0x09a1d805,0x3339d808,0x299d7d48,0x73eda753,
    0x00000000,0x00000000,0x00000000,0x00000000
};

/* fq constants moved to end of file (8-limb form) */

/* ---- G1 generator P = (BLS_G1X, BLS_G1Y) in Montgomery form ---- 
 * Plain x = 0x17f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb
 * Plain y = 0x08b3f481e3aaa0f1a09e30ed741d8ae4fcf5e095d5d00af600db18cb2c04b3edd03cc744a2888ae40caa232946c5e7e1
 */
static const uint32_t BLS_G1X[12] = {   /* x * R mod p */
    0xfd530c16,0x5cb38790,0x9976fff5,0x7817fc67,
    0x143ba1c1,0x154f95c7,0xf3d0e747,0xf0ae6acd,
    0x21dbf440,0xedce6ecc,0x9e0bfb75,0x12017741
};

static const uint32_t BLS_G1Y[12] = {   /* y * R mod p */
    0x0ce72271,0xbaac93d5,0x7918fd8e,0x8c22631a,
    0x570725ce,0xdd595f13,0x50405194,0x51ac5829,
    0xad0059c0,0x0e1c8c3f,0x5008a26a,0x0bbc3efc
};

/* ---- G2 generator Q in Montgomery form (each Fp2 component as two Fp elements) ----
 * x = G2X0 + G2X1 * u
 * y = G2Y0 + G2Y1 * u
 * where u^2 = -1 in Fp2
 */
static const uint32_t BLS_G2X0[12] = {
    0x02940a10,0xf5f28fa2,0x87b4961a,0xb3f5fb26,
    0x3e2ae580,0xa1a893b5,0x1a3caee9,0x9894999d,
    0x1863366b,0x6f67b763,0x4350bcd7,0x05819192
};

static const uint32_t BLS_G2X1[12] = {
    0x9e23f606,0xa5a9c075,0xbccd60c3,0xaaa0c59d,
    0xe2867806,0x3bb17e18,0x8541b367,0x1b1ab6cc,
    0xf2158547,0xc2b6ed0e,0x7360edf3,0x11922a09
};

static const uint32_t BLS_G2Y0[12] = {
    0x60494c4a,0x4c730af8,0x5e369c5a,0x597cfa1f,
    0xaa0a635a,0xe7e6856c,0x6e0d495f,0xbbefb5e9,
    0xf0ef25a2,0x07d3a975,0x7e80dae5,0x0083fd8e
};

static const uint32_t BLS_G2Y1[12] = {
    0xdf64b05d,0xadc0fc92,0x2b1461dc,0x18aa270a,
    0x3be4eba0,0x86adac6a,0xc93da33a,0x79495c4e,
    0xa43ccaed,0xe7175850,0x63de1bf2,0x0b2bc2a1
};

/* ---- Twist constant b' = 4 + 4u in Montgomery form ---- */
/* ---- Twist constant b' = 4 + 4u in Montgomery form ----
 * Both c0 and c1 of b' equal 4*R mod p, so we store one constant
 * and alias both names (saves 48 bytes flash per CU). */
static const uint32_t BLS_FOUR_MONT[12] = {   /* 4 * R mod p */
    0x000cfff3,0xaa270000,0xfc34000a,0x53cc0032,
    0x6b0a807f,0x478fe97a,0xe6ba24d7,0xb1d37ebe,
    0xbf78ab2f,0x8ec9733b,0x3d83de7e,0x09d64551
};
#define BLS_TWIST_B_C0  BLS_FOUR_MONT
#define BLS_TWIST_B_C1  BLS_FOUR_MONT

/* ---- GT generator e(G1, G2) ---- */
/* Each coefficient stored in Montgomery form (a*R mod p), 12 limbs LE */

static const uint32_t BLS_GT0[12] = {
    0xa02f7be3,0x92a4692e,0x9011e8a5,0x6c0c09d7,
    0x8bf687c6,0x2aa428a8,0xf316404b,0x25483bcb,
    0x61ca0dfc,0x8019a515,0xa66267cd,0x0d237d53};
static const uint32_t BLS_GT1[12] = {
    0x84ef3426,0x963ca33e,0x238d0c91,0xec6df0b5,
    0x03bdb0bc,0xd1deeeb2,0xaa5e170c,0xfdb11f03,
    0x6231e4fc,0x3f02cb36,0x8fa3c7ff,0x0f541f5d};
static const uint32_t BLS_GT2[12] = {
    0x1f17e8b0,0xc34044dc,0x5efc0b98,0x77491dd9,
    0x3023ac2b,0xb8986539,0xb1c7398d,0xd0cfa09c,
    0x6e0d6155,0x75ed7f06,0xa3a616e1,0x1954b3b4};
static const uint32_t BLS_GT3[12] = {
    0xce4777e5,0x2f20bab3,0x24041bc6,0xdc98183a,
    0xa2836ab8,0xd8bb3905,0x130d5207,0xc4d63bd1,
    0xf9360896,0x9f89a1c0,0x45ee380c,0x115a6772};
static const uint32_t BLS_GT4[12] = {
    0x19ade228,0xd5357d8b,0x68c2d0b7,0x1c7fcaf5,
    0x4bde2c13,0x2125ced2,0x17accd3d,0x184ad051,
    0x3b77c14b,0x59af0c92,0x12d4ff4d,0x076fb5e5};
static const uint32_t BLS_GT5[12] = {
    0xce99b5b0,0x6f900467,0x995350d1,0xaae46487,
    0x6211acd6,0x208fc835,0x8d8eb84b,0xc88fc54e,
    0xa15930e6,0xc9cc5c0e,0x62ab63c8,0x0e0348db};
static const uint32_t BLS_GT6[12] = {
    0xa9815507,0x4510dbd9,0xceaf6344,0xa058bbdc,
    0x6164e768,0xa4093c62,0x11eedaf6,0x3711c1db,
    0x455819e7,0x35aa44d1,0x3f75d136,0x1917ce86};
static const uint32_t BLS_GT7[12] = {
    0x06f5c1a0,0x573696f2,0x9ec8f11b,0x84a411e0,
    0x726a9c2c,0x4ed3d771,0xd3899b2e,0xb443484d,
    0xf4e5be2c,0x92105566,0x57ebadfb,0x03aae555};
static const uint32_t BLS_GT8[12] = {
    0xb76ab492,0x71f647e6,0x664308db,0xef6914f7,
    0x9138900e,0x46bbcb4e,0x71af7bfa,0x276b4c76,
    0xb4263440,0x49a154f8,0x066abdf0,0x13911c4e};
static const uint32_t BLS_GT9[12] = {
    0x63e27516,0xe3c004aa,0x43a69720,0x66b259c7,
    0x76e92ac8,0x123df761,0xe8362c99,0x8e831f19,
    0x1eb9fd8d,0x9a28ddb0,0x93ca1076,0x14759f7a};
static const uint32_t BLS_GT10[12] = {
    0x59d58416,0xc7942b8d,0x9fac37d9,0x4acc036e,
    0x11f27c14,0x49c09eb7,0x378c498c,0xea713276,
    0x0a555543,0xb0c03779,0x76d1a47d,0x19ef7887};
static const uint32_t BLS_GT11[12] = {
    0xe8621dcf,0x4bb6d760,0x7091ee69,0x825e20b7,
    0x81a9a0c4,0xfd7ce9cb,0xf63a3063,0xd66f3438,
    0xf0c6efd0,0xf58e8597,0x2806f828,0x01af7ed4};

/* ---- AmorE protocol parameters ---- */
#define AMORE_PHI    90u   /* short scalar bits (efficiency parameter, curve-independent) */

/* ---- BLS12-381 scalar field (Fq) constants ---- */
static const uint32_t BLS_Q_FQ[8] = {
    0x00000001,0xffffffff,0xfffe5bfe,0x53bda402,0x09a1d805,0x3339d808,0x299d7d48,0x73eda753 };

#define BLS_N0P_FQ  0xffffffffu   /* -q^(-1) mod 2^32 */

static const uint32_t BLS_R_FQ[8] = {        /* R = 2^256 mod q */
    0xfffffffe,0x00000001,0x00034802,0x5884b7fa,0xecbc4ff5,0x998c4fef,0xacc5056f,0x1824b159 };

static const uint32_t BLS_R2_FQ[8] = {       /* R^2 mod q */
    0xf3f29c6d,0xc999e990,0x87925c23,0x2b6cedcb,0x7254398f,0x05d31496,0x9f59ff11,0x0748d9d9 };

/* q - 2 for Fermat inversion */
static const uint32_t BLS_Q_MINUS_2_FQ[8] = {
    0xffffffff,0xfffffffe,0xfffe5bfe,0x53bda402,0x09a1d805,0x3339d808,0x299d7d48,0x73eda753 };
